### ISSUE TITLE
Homebrew?

### ISSUE THREAD

**Issue by f** [jwoertink/fez#1]
What about creating Homebrew package?

PS. Me and @sdogruyol was thinking a project like this but had no time to. It's a good initiative, thanks! 👍 Keep up good work!

**Comment by jwoertink** [comment]
A homebrew package would be pretty cool. I was originally going to write it in ruby, actually. My only issue was visibility to the community. The http://crystalshards.xyz/ site does a pretty good job of getting the word out there on new packages, so I just wanted to make sure that people saw it. 

I do like the idea though. Would you think the package would install just the executable, or the entire repo? My thought would be the executable, but I've had issues compiling and distributing packages. Maybe you can help me with that once I get this portion working?

**Comment by jwoertink** [comment]
@f Just thinking about this, if I make a homebrew package for this, would it be weird to include crystal as a dependency? First thought is that it should, but then I think if people don't have crystal installed with homebrew, I don't want it to overwrite the version they're using... What do you think?

**Comment by jwoertink** [comment]
Boom https://github.com/jwoertink/homebrew-fez

```
brew tap jwoertink/fez
brew install fez
```
