### ISSUE TITLE
Watch for views

### ISSUE THREAD

**Issue by sdogruyol** [jwoertink/fez#10]
Can i do something like this?

``` ruby
# Watches your main kemal app
guard "kemal", path: ".", file: "app.cr" do
  watch("src/app.cr")
  watch("src/views")
end
```

**Comment by jwoertink** [comment]
Technically, yes, you should be able to. I think you might need a regex for the view files. If you want, make an issue on guard-kemal and I'll add it in so you can specify view files without crazy regex

~Jeremy

**Comment by sdogruyol** [comment]
Closing in favor of https://github.com/jwoertink/guard-kemal/issues/2
