### ISSUE TITLE
Open Discussion on API generation

### ISSUE THREAD

**Issue by jwoertink** [jwoertink/fez#12]
One feature I'm actually in need of right now is being able to generate API apps. These are apps I would consider to be "headless" (e.g. no views). 

My definition of an API app would be:
- Provides routes that do not respond to HTML
- No views (this could be debatable if you consider something like [jbuilder](https://github.com/rails/jbuilder))
- No javascripts
- No CSS

Additional features that I generally use for my APIs are:
- Extra headers for versioning routes
- Being able to version routes
- Ability to authenticate route access by special tokens and such

I would like to make it easy to do a JSON API, XML API, Msgpack API, etc... Choosing your output should be trivial, but would require some sort of serialization. This probably means a serializer shard would be necessary. The question though is, what is our starting data structure that we are serializing? A Model? that means we assume there's a database. A Hash? maybe....

Doing versioning in routes is also tricky since it can change based on the developers preference. Do you version by URL `/v1/things/this.json` or do you use a header `env.headers['Accept'] = 'api+v1.json'`? This would probably need to be a separate shard as well to allow for using either way. But then we need to think about how Kemal does routing, and this could get a bit messy with all these macros..

I would like to leave this as an open discussion. How do you setup your APIs with Kemal? (or how would you?). What sort of things do you need in your API? Are there any good shards you've seen that will help?

**Comment by johnjansen** [comment]
have you had a look at https://github.com/ruby-grape/grape for inspriation?

**Comment by jwoertink** [comment]
Yup. I've used it in a project before. I want to get a feel for how others set up their APIs, and if anyone has already built an API with Kemal, how was it structured? what was used?

**Comment by johnjansen** [comment]
i figured as much ;-) ... so ive got a prod api running, but since its more sinatra than rails, i cut everything by hand. the only real issue i still have to handle is auth, for now this api is private (only accessible from the local network).

i went down the version in route path because it was more explicit IMO and the HOW more transparent. also i felt that requests to it were arguably simpler

**Comment by jwoertink** [comment]
I've pushed up the first version of API generation. Closing this out
