### ISSUE TITLE
Can not install fez through Homebrew

### ISSUE THREAD

**Issue by thegreyfellow** [jwoertink/fez#16]
I am trying to install fez through brew like you said on the installation note, the `tap` command works but install doesn't, and I get this error trying to install:

==> Installing fez from jwoertink/fez
==> Downloading https://github.com/jwoertink/fez/archive/0.10.0.tar.gz
Already downloaded: /Users/<username>/Library/Caches/Homebrew/fez-0.10.0.tar.gz
Error: No such file or directory - /private/tmp/fez-20180128-20817-1pprqhi/fez-0.10.0/fez

Any help would be much appreciated.

**Comment by jwoertink** [comment]
hmm.. I haven't seen that error. Can you try and remove the cache, remove the tap, then try again? Also, what version of homebrew and MacOS are you running?

**Comment by thegreyfellow** [comment]
Okay, I did untap fez and retried but I still get same result:

```
➜ brew tap jwoertink/fez
Updating Homebrew...
==> Tapping jwoertink/fez
Cloning into '/usr/local/Homebrew/Library/Taps/jwoertink/homebrew-fez'...
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Tapped 1 formula (26 files, 20KB)

➜ brew install fez
==> Installing fez from jwoertink/fez
==> Downloading https://github.com/jwoertink/fez/archive/0.10.0.tar.gz
Already downloaded: /Users/<username>/Library/Caches/Homebrew/fez-0.10.0.tar.gz
Error: No such file or directory - /private/tmp/fez-20180129-67015-hobbvc/fez-0.10.0/fez
```

Homebrew version:
`Homebrew 1.5.2
Homebrew/homebrew-core (git revision ee727; last commit 2018-01-29)`
MacOS version:
`High Sierra 10.13.2`

**Comment by jwoertink** [comment]
Cool. Thanks for the info. I'm digging in to see what's up

**Comment by jwoertink** [comment]
Ok, just pushed an update. You will want to clear the fez cache in `brew --cache`, make sure you `brew uninstall fez` (which should fail), and `brew untap jwoertink/fez`. Then go through the normal install and let me know if that works for you.

**Comment by thegreyfellow** [comment]
Awesome! I did just as you said and it's working fine. Thank you for your help :-)

**Comment by jwoertink** [comment]
Sweet! Thanks for the help
