### ISSUE TITLE
Reloader

### ISSUE THREAD

**Issue by russ** [jwoertink/fez#2]
I would love to have something like [Sinatra::Reload](http://www.sinatrarb.com/contrib/reloader.html). Not sure how that can be done but it would make development so much easier.

**Comment by jwoertink** [comment]
I've added Guard and a `guard-kemal` plugin that will watch your files to reload them. Added in [this commit](https://github.com/jwoertink/fez/commit/0b06f51e8ee4d2e3c85e819f03562f49a8984b2e)
