### ISSUE TITLE
Guard doesn't watch es6 file's change, and script tag's attribute and path are wrong.

### ISSUE THREAD

**Issue by Kanezoh** [jwoertink/fez#26]
I found that Guardfile doesn't detect es6 file's change. It is because regex is wrong.

https://github.com/jwoertink/fez/blob/8d55d83ee3b81d7fbf61e1a8f29c7eae8968c988/src/templates/ecr/Guardfile_tmpl#L10-L11

`/src\/assets\/scripts\/\.es6$/` matches `src/assets/scripts/.es6`, so it doesn't make sense.

And I also found that the attribute of the script tag of html is wrong. There are no files `public/javascripts/site.js`, but application.js and the location of file should be designated by "src" attribute.

https://github.com/jwoertink/fez/blob/8d55d83ee3b81d7fbf61e1a8f29c7eae8968c988/src/templates/ecr/src/views/layouts/layout.ecr_tmpl#L13-L16

**Comment by Kanezoh** [comment]
This problem is fixed by #27.
And if you like it, I'd like to add js extension to regexp, like

`watch(/src\/assets\/scripts\/.*\.(es6|js)$/) { `ruby es2js.rb` }`

**Comment by jwoertink** [comment]
Thanks for fixing this! I've released a patch update
